server:
  port: 8887


#  GitHub配置

github:
  client:
    id: Iv1.160de4e8641db070
    secret: 2e3bb0914c73af54b801e493162ca637300f3a13
  redirect:
    uri: http://localhost:8887/callback









#spring:
#  thymeleaf:
#    mode: HTML
#    encoding: UTF-8
#    prefix: classpath:/templates/
#    suffix: html
#    servlet:
#      content-type: text/html
#    cache: false